[package]
name = "kv-store"
version = "0.1.0"
edition = "2024"
# Min version with edition 2024
rust-version = "1.85" 
description = "In-memory key-value store build from tokio tasks, with communication over channels."

[dependencies]
anyhow = "1.0.104"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "io-util", "io-std"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
unwrap_used = "warn"
expect_used = "warn"
